# Generated by Django 3.2.2 on 2021-05-12 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField(blank=True)),
                ('exp_name', models.CharField(blank=True, max_length=100)),
                ('aim', models.TextField(blank=True)),
                ('procedure', models.TextField(blank=True)),
                ('calculations', models.FileField(blank=True, upload_to='')),
                ('precautions', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=25)),
                ('student_enroll_num', models.CharField(blank=True, max_length=50)),
                ('student_email', models.EmailField(blank=True, max_length=254)),
                ('submission_file', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='pass', max_length=25),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Simplab_API.user')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_image', models.FileField(blank=True, upload_to='')),
                ('organization', models.CharField(blank=True, default='not selected', max_length=15)),
                ('contact', models.CharField(blank=True, default='+911234567890', max_length=15)),
                ('teams', models.ManyToManyField(blank=True, related_name='all_teams_enrolled', to='Simplab_API.Team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='all_students_enrolled', to='Simplab_API.User'),
        ),
        migrations.CreateModel(
            name='Experiment_Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField(auto_now_add=True)),
                ('exp', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Simplab_API.experiment')),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Simplab_API.team')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('message', models.TextField(blank=True)),
                ('is_file', models.BooleanField(blank=True, default=False)),
                ('chat_file', models.FileField(blank=True, upload_to='')),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Simplab_API.user')),
                ('team', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Simplab_API.team')),
            ],
        ),
    ]
