# Generated by Django 3.2.2 on 2021-05-12 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0002_auto_20210512_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Simplab_API.user'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Simplab_API.team'),
        ),
        migrations.AlterField(
            model_name='experiment_assignment',
            name='exp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Simplab_API.experiment'),
        ),
        migrations.AlterField(
            model_name='experiment_assignment',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Simplab_API.team'),
        ),
    ]
