# Generated by Django 3.2.2 on 2021-05-17 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0003_auto_20210517_0521'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('due_time', models.TimeField()),
                ('exp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Simplab_API.experiment')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_team_experiments', to='Simplab_API.team')),
            ],
        ),
        migrations.DeleteModel(
            name='Experiment_Assignment',
        ),
    ]
