# Generated by Django 3.2.2 on 2021-05-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0003_auto_20210512_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
