# Generated by Django 3.2.2 on 2021-05-12 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0004_alter_user_detail_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_file',
            field=models.FileField(blank=True, upload_to='chat_files'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='calculations',
            field=models.ImageField(blank=True, upload_to='exp_images'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_file',
            field=models.FileField(blank=True, upload_to='submission_files'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
