# Generated by Django 3.2.2 on 2021-05-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0004_auto_20210517_0529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ass_Submission',
            new_name='AssignmentSubmission',
        ),
    ]
