# Generated by Django 3.2.2 on 2021-05-12 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0005_auto_20210512_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detail',
            old_name='user',
            new_name='username',
        ),
    ]
