# Generated by Django 3.2.2 on 2021-05-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0006_rename_user_user_detail_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detail',
            old_name='username',
            new_name='user',
        ),
    ]
