# Generated by Django 3.2.2 on 2021-05-12 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0007_rename_username_user_detail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Simplab_API.user'),
            preserve_default=False,
        ),
    ]
