# Generated by Django 3.2.2 on 2021-05-18 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0006_assignmentsubmission_assignment'),
        ('Simplab_API', '0007_alter_user_detail_profile_image'),
    ]

    operations = [
    ]
