# Generated by Django 3.2.2 on 2021-05-19 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0008_merge_20210518_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='submission_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
