# Generated by Django 3.2.2 on 2021-05-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0009_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='username',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
