# Generated by Django 3.2.2 on 2021-05-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0010_auto_20210519_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='profile_image',
            field=models.ImageField(blank=True, default='/media/profile_images/default_TG1k14D.jpg', upload_to='profile_images'),
        ),
    ]
