# Generated by Django 3.2.2 on 2021-05-21 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0012_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('email', models.EmailField(blank=True, default='g@g.com', max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Simplab_API.user_auth'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Simplab_API.user_auth'),
        ),
        migrations.AlterField(
            model_name='team',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Simplab_API.user_auth'),
        ),
        migrations.AlterField(
            model_name='team',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='all_member_teams', to='Simplab_API.User_Auth'),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Simplab_API.user_auth'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
