# Generated by Django 3.2.2 on 2021-05-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0014_auto_20210521_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
