# Generated by Django 3.2.2 on 2021-05-13 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0014_auto_20210513_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
