# Generated by Django 3.2.2 on 2021-05-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0015_alter_user_detail_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='exp_observations_image',
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='exp_obs',
            field=models.TextField(default='h'),
        ),
    ]
