# Generated by Django 3.2.2 on 2021-05-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0015_alter_chat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='all_students_enrolled', to='Simplab_API.User'),
        ),
    ]
