# Generated by Django 3.2.2 on 2021-05-14 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0017_userdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='teams',
        ),
        migrations.DeleteModel(
            name='Userdetail',
        ),
    ]
