# Generated by Django 3.2.2 on 2021-05-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0018_auto_20210514_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
