# Generated by Django 3.2.2 on 2021-05-14 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0019_alter_user_detail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='all_member_teams', to='Simplab_API.User'),
        ),
    ]
