# Generated by Django 3.2.2 on 2021-05-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0022_alter_team_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='team_members', to='Simplab_API.Team'),
        ),
    ]
