# Generated by Django 3.2.2 on 2021-05-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Simplab_API', '0024_alter_experiment_assignment_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='teams',
        ),
    ]
